// rapid_gcounter.cpp
// Integrates RAPID dissemination inside the gcounter app.
//
// Build:
// g++ -O2 -std=c++17 -pthread -o rapid_gcounter rapid_gcounter.cpp -I/path/to/nlohmann
//
// Note: adjust include path for delta-crdts.cc if needed.

#include <iostream>
#include <fstream>
#include <thread>
#include <chrono>
#include <atomic>
#include <vector>
#include <string>
#include <random>
#include <map>
#include <csignal>
#include <cstring>
#include <nlohmann/json.hpp>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <unistd.h>
#include <mutex>
#include <queue>
#include <condition_variable>
#include <sstream>
#include <algorithm>
#include <unordered_map>

#include "/home/mace/git/delta-enabled-crdts/delta-crdts.cc"

using json = nlohmann::json;
using namespace std::chrono_literals;

constexpr size_t MSG_MAX = 8192;
static const double BETA = 2.5;
static const int CACHE_TTL = 60; // seconds
static const int HEARTBEAT_INTERVAL_MS = 1000;
static const int GOSSIP_INTERVAL_MS = 1000;
static const int SHORT_JITTER_MIN_MS = 10;
static const int SHORT_JITTER_MAX_MS = 40;
static const int LONG_JITTER_MIN_MS = 200;
static const int LONG_JITTER_MAX_MS = 600;
static const int PORT_DEFAULT = 9000;

std::mutex _gc_mutex;

// CRDT operations (states) send queue (ops generated by app)
std::queue<gcounter<int, std::string>> _ops_send_queue;
std::mutex _ops_queue_mutex;
std::condition_variable _ops_q_cv;

struct node_config {
    std::string id;
    std::string listen_addr;
    std::vector<std::string> peers;
    double ops_per_sec;
    int duration;
    std::string distribution;
    int seed;
    std::string log_file;
    double monitor_interval;
};

struct stats {
    std::atomic<int> sent_msgs{0};
    std::atomic<int> recv_msgs{0};
    std::atomic<int> sent_bytes{0};
    std::atomic<int> recv_bytes{0};
};

// helper: print config
void print_config(const node_config& nc) {
    std::cout << "===== RAPID (GOSSIP) APPLICATION =====" << "\n";
    std::cout << "node id: " << nc.id << "\n";
    std::cout << "listen: " << nc.listen_addr << "\n";
    std::cout << "ops_per_sec: " << nc.ops_per_sec << "\n";
    std::cout << "duration: " << nc.duration << "\n";
    std::cout << "seed: " << nc.seed << "\n";
    std::cout << "monitor_interval: " << nc.monitor_interval << "\n";
    std::cout << "peers: ";
    for (auto &p : nc.peers) {
        std::cout << p << " ";
    }
    std::cout << std::endl;
}

// load config (same as before)
node_config load_config(const std::string& cfg_path, const std::string& id) {
    std::ifstream f(cfg_path);
    json cfg = json::parse(f);
    node_config nc;
    nc.id = id;
    try {
        nc.listen_addr = cfg.at("address").at(id);
    } catch (std::exception& e) {
        std::cout << "Node ID " << id << " not found in config file.\n";
        return nc;
    }
    for (auto& [nid, addr] : cfg["address"].items()) {
        if (nid != id) {
            nc.peers.push_back(addr);
        }
    }
    nc.ops_per_sec = cfg.value("ops_per_sec", 1.0);
    nc.duration = cfg.value("duration", 10);
    nc.distribution = cfg.value("distribution", "uniform");
    std::random_device rd;
    nc.seed = cfg.value("seed", rd());
    nc.monitor_interval = cfg.value("monitor_interval", 1.0);
    std::string log_dir = cfg.value("log_dir", ".");
    if (!log_dir.empty() && log_dir.back() != '/') {
        log_dir.push_back('/');
    }
    nc.log_file = log_dir + "node_" + id + ".log";
    return nc;
}

// ------------------ RAPID internal types ------------------

enum MsgType : uint8_t {
    MT_DATA = 1,
    MT_GOSSIP = 2,
    MT_REQUEST = 3,
    MT_HEARTBEAT = 4
};

struct CacheEntry {
    std::chrono::steady_clock::time_point t;
    std::vector<char> payload;
};

struct CastEntry {
    uint64_t msgid;
    double prob;
    std::chrono::steady_clock::time_point when;
    std::vector<char> payload; // serialized CRDT delta
};

// Cast queue - simple vector-backed scheduling
class CastQueue {
    private:
        std::vector<CastEntry> q_;
        std::mutex mu_;
        std::condition_variable cv_;
        
    public:
        void push(const CastEntry &e) {
            std::lock_guard<std::mutex> lg(mu_);
            q_.push_back(e);
            cv_.notify_one();
        }
        // pop the next due entry; returns true if something popped
        bool pop_due(CastEntry &out) {
            std::unique_lock<std::mutex> lk(mu_);
            if (q_.empty()) {
                cv_.wait_for(lk, std::chrono::milliseconds(50));
            }
            auto now = std::chrono::steady_clock::now();
            for (auto it = q_.begin(); it != q_.end(); ++it) {
                if (it->when <= now) {
                    out = *it;
                    q_.erase(it);
                    return true;
                }
            }
            return false;
        }
        void remove_if(uint64_t msgid) {
            std::lock_guard<std::mutex> lg(mu_);
            for (auto it = q_.begin(); it != q_.end(); ) {
                if (it->msgid == msgid) {
                    it = q_.erase(it);
                } else {
                    ++it;
                }
            }
        }
};

// global RAPID state
CastQueue _cast_queue;
std::unordered_map<uint64_t, CacheEntry> _cache;
std::mutex _cache_mutex;
std::unordered_map<uint64_t, std::chrono::steady_clock::time_point> _neighbors;
std::mutex _neighbors_mutex;

// network
int _sockfd = -1;
sockaddr_in _broadcast_addr;
int _listen_port = PORT_DEFAULT;

// RNG
std::mt19937_64 _rng((uint64_t)std::chrono::steady_clock::now().time_since_epoch().count());
std::uniform_real_distribution<double> _uniform_01(0.0, 1.0);

// helpers to generate msgid
uint64_t gen_id() {
    return _rng();
}

// build packets (simple binary)
void append_uint64(std::vector<char>& v, uint64_t x) {
    for (int i = 0; i < 8; ++i) {
        v.push_back(static_cast<char>((x >> (i*8)) & 0xFF));
    }
}
void append_uint32(std::vector<char>& v, uint32_t x) {
    for (int i = 0; i < 4; ++i) {
        v.push_back(static_cast<char>((x >> (i*8)) & 0xFF));
    }
}
uint64_t read_uint64(const char* p) {
    uint64_t x = 0;
    for (int i = 0; i < 8; ++i) {
        x |= (static_cast<uint64_t>(static_cast<unsigned char>(p[i])) << (i*8));
    }
    return x;
}
uint32_t read_uint32(const char* p) {
    uint32_t x = 0;
    for (int i = 0; i < 4; ++i) {
        x |= (static_cast<uint32_t>(static_cast<unsigned char>(p[i])) << (i*8));
    }
    return x;
}

void build_data_packet(uint64_t msgid, const std::vector<char>& payload, std::vector<char>& out) {
    out.clear();
    out.push_back(static_cast<char>(MT_DATA));
    append_uint64(out, msgid);
    append_uint32(out, static_cast<uint32_t>(payload.size()));
    out.insert(out.end(), payload.begin(), payload.end());
}

void build_gossip_packet(const std::vector<uint64_t>& headers, std::vector<char>& out) {
    out.clear();
    out.push_back(static_cast<char>(MT_GOSSIP));
    uint16_t n = static_cast<uint16_t>(headers.size());
    out.push_back(static_cast<char>(n & 0xFF));
    out.push_back(static_cast<char>((n >> 8) & 0xFF));
    for (uint64_t h : headers) {
        append_uint64(out, h);
    }
}

void build_request_packet(uint64_t msgid, std::vector<char>& out) {
    out.clear();
    out.push_back(static_cast<char>(MT_REQUEST));
    append_uint64(out, msgid);
}

void build_heartbeat_packet(uint64_t peerid, std::vector<char>& out) {
    out.clear();
    out.push_back(static_cast<char>(MT_HEARTBEAT));
    append_uint64(out, peerid);
}

// send helpers (to all peers)
void send_broadcast(const std::vector<char>& pkt, stats &st) {
    ssize_t sent = sendto(_sockfd, pkt.data(), pkt.size(), 0, (sockaddr*)&_broadcast_addr, sizeof(_broadcast_addr));
    if (sent > 0) {
        st.sent_msgs++;
        st.sent_bytes += static_cast<int>(sent);
    }
}

// cache helpers
bool cache_exists(uint64_t id) {
    std::lock_guard<std::mutex> lg(_cache_mutex);
    return _cache.find(id) != _cache.end();
}
void cache_insert(uint64_t id, const std::vector<char>& payload) {
    std::lock_guard<std::mutex> lg(_cache_mutex);
    CacheEntry e;
    e.t = std::chrono::steady_clock::now();
    e.payload = payload;
    _cache[id] = std::move(e);
}
bool cache_get(uint64_t id, std::vector<char>& out_payload) {
    std::lock_guard<std::mutex> lg(_cache_mutex);
    auto it = _cache.find(id);
    if (it == _cache.end()) {
        return false;
    }
    out_payload = it->second.payload;
    return true;
}
void cache_cleanup() {
    std::lock_guard<std::mutex> lg(_cache_mutex);
    auto now = std::chrono::steady_clock::now();
    for (auto it = _cache.begin(); it != _cache.end(); ) {
        auto age = std::chrono::duration_cast<std::chrono::seconds>(now - it->second.t).count();
        if (age > CACHE_TTL) {
            it = _cache.erase(it);
        } else {
            ++it;
        }
    }
}

// neighbor helpers
void neighbor_seen(uint64_t id) {
    std::lock_guard<std::mutex> lg(_neighbors_mutex);
    _neighbors[id] = std::chrono::steady_clock::now();
}
int neighbor_count() {
    std::lock_guard<std::mutex> lg(_neighbors_mutex);
    return static_cast<int>(_neighbors.size());
}
void neighbor_cleanup() {
    std::lock_guard<std::mutex> lg(_neighbors_mutex);
    auto now = std::chrono::steady_clock::now();
    for (auto it = _neighbors.begin(); it != _neighbors.end(); ) {
        auto age = std::chrono::duration_cast<std::chrono::seconds>(now - it->second).count();
        if (age > 5) {
            it = _neighbors.erase(it);
        } else {
            ++it;
        }
    }
}

// ---------- Main threads for RAPID ----------

// cast worker: transmits DATA from _cast_queue according to prob rules
void cast_worker(stats &st) {
    std::uniform_int_distribution<int> short_jitter(SHORT_JITTER_MIN_MS, SHORT_JITTER_MAX_MS);
    std::uniform_int_distribution<int> long_jitter(LONG_JITTER_MIN_MS, LONG_JITTER_MAX_MS);
    while (true) {
        CastEntry e;
        if (_cast_queue.pop_due(e)) {
            double r = _uniform_01(_rng);
            if (r <= e.prob) {
                // send data to all peers
                std::vector<char> pkt;
                build_data_packet(e.msgid, e.payload, pkt);
                send_broadcast(pkt, st);
            } else {
                // schedule longer reattempt
                e.when = std::chrono::steady_clock::now() + std::chrono::milliseconds(long_jitter(_rng));
                e.prob = 1.0; // escalate to certain forward after delay as RAPID suggests
                _cast_queue.push(e);
            }
        } else {
            // no due entry, tiny sleep
            std::this_thread::sleep_for(5ms);
        }
    }
}

// gossip worker: periodically gossip headers of recent messages
void gossip_worker(stats &st) {
    while (true) {
        std::this_thread::sleep_for(std::chrono::milliseconds(GOSSIP_INTERVAL_MS));
        // collect up to N headers from cache
        std::vector<uint64_t> headers;
        {
            std::lock_guard<std::mutex> lg(_cache_mutex);
            int taken = 0;
            for (auto &kv : _cache) {
                headers.push_back(kv.first);
                ++taken;
                if (taken >= 50) {
                    break;
                }
            }
        }
        if (!headers.empty()) {
            std::vector<char> pkt;
            build_gossip_packet(headers, pkt);
            send_broadcast(pkt, st);
        }
    }
}

// heartbeat worker: periodically send heartbeat
void heartbeat_worker(uint64_t selfid, stats &st) {
    while (true) {
        std::vector<char> pkt;
        build_heartbeat_packet(selfid, pkt);
        send_broadcast(pkt, st);
        std::this_thread::sleep_for(std::chrono::milliseconds(HEARTBEAT_INTERVAL_MS));
    }
}

// request worker not strictly necessary in some flows (requests are sent when gossip headers indicate missing DATA).
// Here we just let recv_loop schedule requests into _cast_queue with small jitter and prob=1 (we'll use cast queue to send requests? better keep separate).
void send_request_once(uint64_t msgid, stats &st) {
    std::vector<char> pkt;
    build_request_packet(msgid, pkt);
    send_broadcast(pkt, st);
}

// recv loop: handle incoming packets
void recv_loop(int sockfd_local, gcounter<int, std::string>& gc, stats& st) {
    char buf[MSG_MAX];
    sockaddr_in src;
    socklen_t srclen = sizeof(src);
    while (true) {
        ssize_t n = recvfrom(sockfd_local, buf, MSG_MAX, 0, (sockaddr*)&src, &srclen);
        if (n <= 0) {
            std::this_thread::sleep_for(1ms);
            continue;
        }
        uint8_t type = static_cast<uint8_t>(buf[0]);
        if (type == MT_DATA) {
            if (n < 1 + 8 + 4) {
                continue;
            }
            uint64_t msgid = read_uint64(buf + 1);
            uint32_t len = read_uint32(buf + 1 + 8);
            if (1 + 8 + 4 + (ssize_t)len > n) {
                continue;
            }
            const char* payload_ptr = buf + 1 + 8 + 4;
            std::vector<char> payload(payload_ptr, payload_ptr + len);
            // If not seen, deliver and schedule forwarding
            if (!cache_exists(msgid)) {
                cache_insert(msgid, payload);
                // deliver to CRDT
                try {
                    std::string s(payload.begin(), payload.end());
                    auto recv_gc = gcounter<int, std::string>::deserialize(s);
                    {
                        std::unique_lock<std::mutex> lg(_gc_mutex);
                        gc.join(recv_gc);
                    }
                    st.recv_msgs++;
                    st.recv_bytes += static_cast<int>(len);
                } catch (...) {
                    // parse error: ignore
                }
                // compute prob
                int ncount = neighbor_count();
                double pr = BETA / std::max(1, ncount);
                if (pr > 1.0) {
                    pr = 1.0;
                }
                CastEntry e;
                e.msgid = msgid;
                e.prob = pr;
                e.when = std::chrono::steady_clock::now() + std::chrono::milliseconds((int)(_uniform_01(_rng)*(SHORT_JITTER_MAX_MS-SHORT_JITTER_MIN_MS) + SHORT_JITTER_MIN_MS));
                e.payload = payload;
                _cast_queue.push(e);
            } else {
                // already seen: ignore but can update cache timestamp
            }
        } else if (type == MT_GOSSIP) {
            if (n < 1 + 2) {
                continue;
            }
            uint16_t nn = static_cast<uint16_t>(static_cast<unsigned char>(buf[1]) | (static_cast<unsigned char>(buf[2])<<8));
            const char* p = buf + 3;
            for (int i = 0; i < (int)nn; ++i) {
                if (p + 8 > buf + n) {
                    break;
                }
                uint64_t hid = read_uint64(p);
                p += 8;
                if (!cache_exists(hid)) {
                    // schedule request with short jitter
                    int jitter = SHORT_JITTER_MIN_MS + (_rng() % (SHORT_JITTER_MAX_MS - SHORT_JITTER_MIN_MS + 1));
                    std::this_thread::sleep_for(std::chrono::milliseconds(jitter)); // small backoff
                    send_request_once(hid, st);
                }
            }
        } else if (type == MT_REQUEST) {
            if (n < 1 + 8) {
                continue;
            }
            uint64_t hid = read_uint64(buf + 1);
            // if we have it, reply with data immediately
            std::vector<char> payload;
            if (cache_get(hid, payload)) {
                std::vector<char> pkt;
                build_data_packet(hid, payload, pkt);
                send_broadcast(pkt, st);
            }
        } else if (type == MT_HEARTBEAT) {
            if (n < 1 + 8) {
                continue;
            }
            uint64_t pid = read_uint64(buf + 1);
            neighbor_seen(pid);
        } else {
            // unknown type: ignore
        }
    }
}

// application-to-rapid: when app generates a delta, we insert into cache and schedule an immediate cast with prob=1
void app_sender_thread(stats &st) {
    while (true) {
        std::unique_lock<std::mutex> lk(_ops_queue_mutex);
        _ops_q_cv.wait(lk, []{
            return !_ops_send_queue.empty();
        });
        gcounter<int, std::string> delta = _ops_send_queue.front();
        _ops_send_queue.pop();
        lk.unlock();
        std::string ser = delta.serialize();
        std::vector<char> payload(ser.begin(), ser.end());
        uint64_t msgid = gen_id();
        cache_insert(msgid, payload);
        // schedule immediate cast with prob=1
        CastEntry e;
        e.msgid = msgid;
        e.prob = 1.0;
        e.when = std::chrono::steady_clock::now(); // immediate
        e.payload = payload;
        _cast_queue.push(e);
        // also gossip header quickly (piggyback will do later)
        // stats
        st.sent_msgs++;
        st.sent_bytes += static_cast<int>(payload.size());
    }
}

// monitor loop (unchanged)
void monitor_loop(gcounter<int, std::string>& gc, stats& stats_ref, double interval, const std::string& logfile) {
    std::ofstream log(logfile, std::ios::trunc);
    if (!log.is_open()) {
        std::cerr << "Warning: cannot open log file: " << logfile << "\n";
    }
    while (true) {
        std::this_thread::sleep_for(std::chrono::duration<double>(interval));
        int local = gc.local();
        int total = gc.read();
        std::ostringstream oss;
        oss << std::fixed << std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count()
            << ", local=" << local << ", total=" << total
            << ", sent_msgs=" << stats_ref.sent_msgs
            << ", recv_msgs=" << stats_ref.recv_msgs
            << ", sent_bytes=" << stats_ref.sent_bytes
            << ", recv_bytes=" << stats_ref.recv_bytes << "\n";
        std::string line = oss.str();
        std::cout << line << std::flush;
        if (log.is_open()) {
            log << line << std::flush;
        }
    }
}

// run_random_mode: push generated deltas to _ops_send_queue (same as earlier but without direct send)
void run_random_mode(const node_config& nc, gcounter<int, std::string>& gc) {
    double ops_per_sec = nc.ops_per_sec;
    double duration = nc.duration;
    unsigned seed = nc.seed;
    std::default_random_engine gen(seed);
    std::exponential_distribution<double> expd(ops_per_sec);
    auto start = std::chrono::steady_clock::now();
    while (true) {
        double elapsed = std::chrono::duration<double>(std::chrono::steady_clock::now() - start).count();
        if (elapsed > duration) {
            break;
        }
        double wait = expd(gen);
        std::this_thread::sleep_for(std::chrono::duration<double>(wait));
        std::uniform_int_distribution<int> inc_dist(1, 10);
        int val = inc_dist(gen);
        gcounter<int, std::string> delta_obj;
        {
            std::unique_lock<std::mutex> lg(_gc_mutex);
            delta_obj = gc.inc(val);
        }
        {
            std::unique_lock<std::mutex> lk(_ops_queue_mutex);
            _ops_send_queue.push(delta_obj);
            _ops_q_cv.notify_one();
        }
    }
}

// setup socket and peers
bool setup_socket_and_peers(const node_config& nc) {
    // parse listen addr
    auto pos = nc.listen_addr.find(':');
    if (pos == std::string::npos) {
        std::cerr << "Invalid listen_addr\n";
        return false;
    }
    std::string self_ip = nc.listen_addr.substr(0, pos);
    _listen_port = std::stoi(nc.listen_addr.substr(pos + 1));

    // create udp socket
    _sockfd = socket(AF_INET, SOCK_DGRAM, 0);
    if (_sockfd < 0) {
        perror("socket");
        return false;
    }
    int reuse = 1;
    setsockopt(_sockfd, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse));
    
    int bc = 1;
    setsockopt(_sockfd, SOL_SOCKET, SO_BROADCAST, &bc, sizeof(bc));
    sockaddr_in addr{};
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port = htons(_listen_port);
    if (bind(_sockfd, (sockaddr*)&addr, sizeof(addr)) < 0) {
        perror("bind");
        close(_sockfd);
        return false;
    }
    
    // configure broadcast out socket
    sockaddr_in broadcast{};
    broadcast.sin_family = AF_INET;
    broadcast.sin_port = htons(_listen_port);
    broadcast.sin_addr.s_addr = INADDR_BROADCAST;
    _broadcast_addr = broadcast;

    return true;
}

// cleanup threads: cache+neighbors
void periodic_maintenance() {
    while (true) {
        cache_cleanup();
        neighbor_cleanup();
        std::this_thread::sleep_for(std::chrono::seconds(5));
    }
}

// main
int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr << "Usage: " << argv[0] << " -id <ID> -config <config.json>\n";
        return 1;
    }
    std::string node_id;
    std::string cfgfile;
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "-id" && i + 1 < argc) {
            node_id = argv[++i];
        } else if (arg == "-config" && i + 1 < argc) {
            cfgfile = argv[++i];
        }
    }
    if (node_id.empty() || cfgfile.empty()) {
        std::cerr << "Missing node ID or config file.\n";
        return 1;
    }
    node_config nc = load_config(cfgfile, node_id);
    print_config(nc);
    if (nc.listen_addr.empty()) {
        std::cerr << "Invalid configuration for node " << node_id << "\n";
        return 1;
    }
    stats st;
    if (!setup_socket_and_peers(nc)) {
        std::cerr << "Failed to setup network\n";
        return 1;
    }
    gcounter<int, std::string> gc(nc.id);
    // self id for heartbeat
    uint64_t selfid = gen_id();
    // start threads
    std::thread t_recv(recv_loop, _sockfd, std::ref(gc), std::ref(st));
    t_recv.detach();
    std::thread t_cast(cast_worker, std::ref(st));
    t_cast.detach();
    std::thread t_gossip(gossip_worker, std::ref(st));
    t_gossip.detach();
    std::thread t_hb(heartbeat_worker, selfid, std::ref(st));
    t_hb.detach();
    std::thread t_app_sender(app_sender_thread, std::ref(st));
    t_app_sender.detach();
    std::thread t_mon(monitor_loop, std::ref(gc), std::ref(st), nc.monitor_interval, nc.log_file);
    t_mon.detach();
    std::thread t_maint(periodic_maintenance);
    t_maint.detach();
    // run workload: use same function but now it enqueues to _ops_send_queue
    run_random_mode(nc, gc);
    // wait a bit to let dissemination finish
    std::this_thread::sleep_for(15s);
    std::cout << "FINAL local=" << gc.local()
              << " total=" << gc.read()
              << " sent=" << st.sent_msgs
              << " recv=" << st.recv_msgs << std::endl;
    close(_sockfd);
    return 0;
}
